services:
  mongodb:
    image: mongo:8
    container_name: learnly-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - learnly-mongo-data:/data/db

volumes:
  learnly-mongo-data:
