server.port=8080
spring.application.name=learnly-spring-api
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=learnly

jwt.secret=kingobreezy#zayneisgoated1300TheConFounders
jwt.expiration=86400000


