server.port=8080
spring.application.name=learnly-spring-api
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=learnly

jwt.secret=kingobreezy#zayneisgoated1300TheConFounders
jwt.expiration=600000

learnly.admin.email=@admin@learnly.co.za
learnly.admin.password=theconfoundingfathers
learnly.admin.firstName=Learnly
learnly.admin.lastName=Admin



#For admin review, 20% of random self claimed modules will be selected for verification if they really were completed
#slepot
learnly.verification.spot-check-rate=0.2
spring.web.cors.allowed-origins=http://localhost:5173


